<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="3246" started-at="2021-01-19T14:03:37Z" finished-at="2021-01-19T14:03:40Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="3246" started-at="2021-01-19T14:03:37Z" finished-at="2021-01-19T14:03:40Z">
      <class name="testpages.ValidatingTotalAmount">
        <test-method status="PASS" signature="killAllnode()[pri:0, instance:testpages.ValidatingTotalAmount@23529fee]" name="killAllnode" is-config="true" duration-ms="3103" started-at="2021-01-19T19:33:37Z" finished-at="2021-01-19T19:33:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- killAllnode -->
        <test-method status="FAIL" signature="ValidateAmount(java.lang.String)[pri:0, instance:testpages.ValidatingTotalAmount@23529fee]" name="ValidateAmount" duration-ms="0" started-at="2021-01-19T19:33:40Z" data-provider="inputData" finished-at="2021-01-19T19:33:40Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
DataProvider should be static: public java.lang.Object[][] utlize.TestData.getData()]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
DataProvider should be static: public java.lang.Object[][] utlize.TestData.getData()
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:328)
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:262)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:414)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateAmount -->
      </class> <!-- testpages.ValidatingTotalAmount -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
